[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hot_jupiter"
version = "0.1.0"
description = "Giant Planet Thermal Evolution Model"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.ruff.lint]
ignore = ["E501", "C408"]

[tool.pytest.ini_options]
testpaths = ["hot_jupiter"]
python_files = ["test_*.py", "*_test.py"]
