// Copyright 2026 Antigravity Scientific Automation & Multi-Physics Discovery Campaign
// Frontier 6: Ocean-Freezing Pressurization & Viscoelastic Cryosphere Fracture Engine

#ifndef CPP_INCLUDE_CRYOSPHERE_FRACTURE_DISCOVERY_HPP_
#define CPP_INCLUDE_CRYOSPHERE_FRACTURE_DISCOVERY_HPP_

#include <vector>
#include <cmath>
#include <string>
#include <algorithm>
#include "cpp/include/constants.hpp"

namespace hot_jupiter {

enum class CryosphereFailureMode {
  BRITTLE_TENSILE_RUPTURE,
  DUCTILE_VISCOUS_RELAXATION,
  QUIESCENT_OCEAN_RETENTION
};

struct CryosphereState {
  double time_myr;
  double ice_shell_thickness_km;
  double ocean_thickness_km;
  double ocean_overpressure_mpa;
  double surface_hoop_stress_mpa;
  double maxwell_relaxation_time_yr;
  bool is_fractured;
};

class CryosphereFractureDiscoveryEngine {
 public:
  CryosphereFractureDiscoveryEngine()
      : body_radius_km_(606.0), surface_gravity_m_s2_(0.288), bulk_density_kg_m3_(1700.0),
        shear_modulus_gpa_(3.5), tensile_strength_mpa_(2.0) {}

  CryosphereFractureDiscoveryEngine(double radius_km, double gravity, double density,
                                    double shear_mod_gpa, double tensile_str_mpa)
      : body_radius_km_(radius_km), surface_gravity_m_s2_(gravity),
        bulk_density_kg_m3_(density), shear_modulus_gpa_(shear_mod_gpa),
        tensile_strength_mpa_(tensile_str_mpa) {}

  // Volumetric expansion of water to ice Ih (delta V / V = +0.09)
  double VolumetricExpansionFraction() const {
    return 0.09;
  }

  // Temperature-dependent ice viscosity: eta(T) = eta_0 * exp( Q/R * (1/T - 1/T_melt) )
  double IceViscosityPaS(double temperature_k) const {
    double t_melt = 273.15;
    double t_clamped = std::clamp(temperature_k, 100.0, 273.0);
    double q_act = 50.0e3;  // Activation energy 50 kJ/mol
    double r_gas = 8.314;
    double eta_0 = 1.0e14;  // Base viscosity near melting point [Pa s]
    return eta_0 * std::exp((q_act / r_gas) * (1.0 / t_clamped - 1.0 / t_melt));
  }

  // Maxwell viscoelastic relaxation timescale: tau_M = eta / mu
  double MaxwellRelaxationTimeYears(double temperature_k) const {
    double eta = IceViscosityPaS(temperature_k);
    double mu_pa = shear_modulus_gpa_ * 1.0e9;
    double tau_s = eta / mu_pa;
    return tau_s / (365.25 * 86400.0);
  }

  // Elastic ocean overpressure generated by freezing a layer of thickness delta_h_ice
  // Delta P = (delta V / V) * delta_h_ice / ( R_ocean * (1 / (4 mu) + 1 / K_water) )
  double ComputeOceanOverpressureMPa(double ice_thickness_km, double ocean_thickness_km,
                                     double frozen_layer_km) const {
    double r_ocean_m = (body_radius_km_ - ice_thickness_km) * 1.0e3;
    if (r_ocean_m <= 1.0e3 || ocean_thickness_km <= 0.1) return 0.0;

    double delta_v_frac = VolumetricExpansionFraction();
    double k_water_pa = 2.0e9;      // Bulk modulus of water 2 GPa
    double mu_ice_pa = shear_modulus_gpa_ * 1.0e9;

    double volume_change_m3 = 4.0 * M_PI * std::pow(r_ocean_m, 2) * (frozen_layer_km * 1.0e3) * delta_v_frac;
    double ocean_volume_m3 = (4.0 / 3.0) * M_PI * (std::pow(r_ocean_m, 3) - std::pow(r_ocean_m - ocean_thickness_km * 1.0e3, 3));

    double compliance = (1.0 / k_water_pa) + (3.0 / (4.0 * mu_ice_pa)) * (body_radius_km_ / std::max(1.0, ice_thickness_km));
    double delta_p_pa = (volume_change_m3 / ocean_volume_m3) / compliance;
    return delta_p_pa / 1.0e6;  // MPa
  }

  // Surface hoop stress on the thin/thick spherical shell: sigma_theta = Delta P * R / (2 * h_ice)
  double ComputeSurfaceHoopStressMPa(double delta_p_mpa, double ice_thickness_km) const {
    double h_eff_km = std::max(1.0, ice_thickness_km);
    return delta_p_mpa * (body_radius_km_ / (2.0 * h_eff_km));
  }

  // Full secular thermal cooling, freezing, and viscoelastic stress evolution
  std::vector<CryosphereState> EvolveFreezingCryosphere(double initial_ice_thickness_km,
                                                       double initial_ocean_thickness_km,
                                                       double lid_temp_k = 120.0,
                                                       double freezing_rate_km_myr = 0.05,
                                                       double t_max_myr = 1000.0,
                                                       double dt_myr = 1.0) const {
    std::vector<CryosphereState> history;
    double h_ice = initial_ice_thickness_km;
    double h_ocean = initial_ocean_thickness_km;
    double accumulated_frozen_km = 0.0;

    double tau_m_yr = MaxwellRelaxationTimeYears(lid_temp_k);
    double tau_m_myr = tau_m_yr / 1.0e6;


    double current_overpressure_mpa = 0.0;
    bool fractured = false;

    for (double t = 0.0; t <= t_max_myr; t += dt_myr) {
      if (h_ocean > 0.1) {
        double delta_freeze = freezing_rate_km_myr * dt_myr;
        delta_freeze = std::min(h_ocean, delta_freeze);
        h_ice += delta_freeze;
        h_ocean -= delta_freeze;
        accumulated_frozen_km += delta_freeze;

        // Elastic pressurization increment
        double delta_p_inc = ComputeOceanOverpressureMPa(h_ice, h_ocean, delta_freeze);
        
        // Viscous relaxation: dP/dt = dP_elastic/dt - P / tau_Maxwell
        double relax_factor = (tau_m_myr > 0.0) ? std::exp(-dt_myr / tau_m_myr) : 0.0;
        current_overpressure_mpa = current_overpressure_mpa * relax_factor + delta_p_inc;
      }

      double hoop_stress = ComputeSurfaceHoopStressMPa(current_overpressure_mpa, h_ice);
      if (hoop_stress >= tensile_strength_mpa_) {
        fractured = true;
      }

      CryosphereState state;
      state.time_myr = t;
      state.ice_shell_thickness_km = h_ice;
      state.ocean_thickness_km = h_ocean;
      state.ocean_overpressure_mpa = current_overpressure_mpa;
      state.surface_hoop_stress_mpa = hoop_stress;
      state.maxwell_relaxation_time_yr = tau_m_yr;
      state.is_fractured = fractured;
      history.push_back(state);

      if (h_ocean <= 0.05) {
        break;
      }
    }
    return history;
  }

  // Classify failure mode
  CryosphereFailureMode ClassifyFailure(const std::vector<CryosphereState>& history) const {
    if (history.empty()) return CryosphereFailureMode::QUIESCENT_OCEAN_RETENTION;
    for (const auto& s : history) {
      if (s.is_fractured) return CryosphereFailureMode::BRITTLE_TENSILE_RUPTURE;
    }
    if (history.back().ocean_thickness_km <= 0.1) {
      return CryosphereFailureMode::DUCTILE_VISCOUS_RELAXATION;
    }
    return CryosphereFailureMode::QUIESCENT_OCEAN_RETENTION;
  }

 private:
  double body_radius_km_;
  double surface_gravity_m_s2_;
  double bulk_density_kg_m3_;
  double shear_modulus_gpa_;
  double tensile_strength_mpa_;
};

}  // namespace hot_jupiter

#endif  // CPP_INCLUDE_CRYOSPHERE_FRACTURE_DISCOVERY_HPP_
