# Copyright 2026 Antigravity Solar System Dynamics Replication Campaign
# Publication-Grade Plot Generator for Paper #196: Goldreich & Soter (1966) "Q in the Solar System"
#
# Generates:
#   1. fig_comparison.pdf / .png: Tidal Q and Love numbers across Solar System bodies
#   2. fig_model_choices.pdf / .png: Despinning timescale tau_despin vs Q and orbital distance
#   3. fig_diagram.pdf / .png: Pedagogical schematic of tidal bulge phase lag angle delta = 1/(2Q)

import csv
import os

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import patches

# Set global publication typography and styling
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 11,
    'axes.labelsize': 12,
    'axes.titlesize': 13,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 14,
    'mathtext.fontset': 'dejavusans',
    'axes.grid': True,
    'grid.alpha': 0.35,
    'grid.linestyle': '--',
})

output_dir = 'replications_ss/paper_196'
os.makedirs(output_dir, exist_ok=True)


# Helper function to read CSV
def read_csv_dict(filepath):
    data = {}
    with open(filepath, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            for k, v in row.items():
                if k not in data:
                    data[k] = []
                data[k].append(v)
    return data


# Load CSV data generated by C++ solver
data_bodies = read_csv_dict(
    os.path.join(output_dir, 'solar_system_q_comparison.csv'))
data_tau = read_csv_dict(
    os.path.join(output_dir, 'despinning_timescales_vs_q.csv'))
data_lag = read_csv_dict(os.path.join(output_dir, 'tidal_lag_angle_vs_q.csv'))
data_moon = read_csv_dict(
    os.path.join(output_dir, 'earth_moon_tidal_recession.csv'))

# ============================================================================
# FIGURE 1: fig_comparison.pdf - Tidal Q and Dissipation across the Solar System
# ============================================================================
fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(13.5, 5.8))

# Panel 1: log10(Q) comparison: Goldreich & Soter (1966) vs Modern Constraints
bodies = np.array(data_bodies['Body'])
q_gs = np.array([float(x) for x in data_bodies['Q_GS1966']])
q_mod = np.array([float(x) for x in data_bodies['Q_Modern']])
categories = np.array(data_bodies['Category'])

x_indices = np.arange(len(bodies))
bar_width = 0.38

bars1 = ax1.bar(x_indices - bar_width / 2,
                np.log10(q_gs),
                bar_width,
                label='Goldreich & Soter (1966)',
                color='#2b5c8f',
                edgecolor='black',
                alpha=0.90)
bars2 = ax1.bar(x_indices + bar_width / 2,
                np.log10(q_mod),
                bar_width,
                label='Modern Benchmark (Juno, Cassini, LLR)',
                color='#d95f02',
                edgecolor='black',
                alpha=0.90)

ax1.set_xticks(x_indices)
ax1.set_xticklabels(bodies, rotation=45, ha='right', fontweight='medium')
ax1.set_ylabel(r'$\log_{10}(Q)$ (Specific Tidal Quality Factor)',
               fontweight='bold')
ax1.set_title(r'(a) Specific Dissipation Factor $Q$ Across Solar System Bodies',
              fontweight='bold',
              pad=10)
ax1.set_ylim(0, 6.0)
ax1.axhline(np.log10(100),
            color='gray',
            linestyle=':',
            lw=1.2,
            label=r'Terrestrial / Rocky Range ($Q \sim 10-100$)')
ax1.axhline(np.log10(1e5),
            color='purple',
            linestyle=':',
            lw=1.2,
            label=r'Giant Planet Range ($Q \sim 10^4-10^6$)')
ax1.legend(loc='upper left', framealpha=0.92, fontsize=9.5)

# Text annotation for R^2
log_gs = np.log10(q_gs)
log_mod = np.log10(q_mod)
ss_res = np.sum((log_mod - log_gs)**2)
ss_tot = np.sum((log_mod - np.mean(log_gs))**2)
r2 = 1.0 - (ss_res / ss_tot)
ax1.text(0.97,
         0.05,
         f'Statistical Concordance $R^2 = {r2:.4f}$',
         transform=ax1.transAxes,
         ha='right',
         va='bottom',
         bbox=dict(boxstyle='round,pad=0.5',
                   facecolor='white',
                   edgecolor='navy',
                   alpha=0.9),
         fontweight='bold',
         color='navy')

# Panel 2: Love Number k2 and Im(k2) = k2 / Q
k2_vals = np.array([float(x) for x in data_bodies['k2']])

scatter = ax2.scatter(k2_vals,
                      q_gs,
                      c=np.log10(q_gs),
                      cmap='viridis',
                      s=120,
                      edgecolors='black',
                      zorder=5)
for i, name in enumerate(bodies):
    offset_x = 0.015
    offset_y = 1.15
    if name in ['Europa', 'Ganymede', 'Titan', 'Triton']:
        offset_y = 0.75 + (i % 2) * 0.4
    ax2.annotate(name, (k2_vals[i], q_gs[i]),
                 xytext=(k2_vals[i] + offset_x, q_gs[i] * offset_y),
                 fontsize=9,
                 fontweight='bold',
                 arrowprops=dict(arrowstyle='->',
                                 lw=0.8,
                                 color='gray',
                                 shrinkA=3,
                                 shrinkB=3))

ax2.set_yscale('log')
ax2.set_xlabel(r'Potential Love Number $k_2$', fontweight='bold')
ax2.set_ylabel(r'Specific Tidal Dissipation Factor $Q$', fontweight='bold')
ax2.set_title(r'(b) Elastic/Fluid Rigidity ($k_2$) vs Dissipation ($Q$)',
              fontweight='bold',
              pad=10)
ax2.set_xlim(-0.02, 0.65)
ax2.set_ylim(5, 3e5)

# Highlight regions
ax2.axvspan(-0.02,
            0.08,
            color='green',
            alpha=0.08,
            label=r'Rigid Moons & Small Planets ($k_2 \leq 0.05$)')
ax2.axvspan(0.10,
            0.35,
            color='blue',
            alpha=0.08,
            label=r'Terrestrial Mantles ($k_2 \approx 0.1-0.35$)')
ax2.axvspan(0.35,
            0.65,
            color='orange',
            alpha=0.08,
            label=r'Fluid Gas Giants ($k_2 \approx 0.35-0.6$)')
ax2.legend(loc='lower right', framealpha=0.92, fontsize=9)

plt.tight_layout()
fig1.savefig(os.path.join(output_dir, 'fig_comparison.pdf'), dpi=300)
fig1.savefig(os.path.join(output_dir, 'fig_comparison.png'), dpi=300)
plt.close(fig1)
print(f'✅ Generated {output_dir}/fig_comparison.pdf and .png')

# ============================================================================
# FIGURE 2: fig_model_choices.pdf - Despinning Timescales vs Q & Distance
# ============================================================================
fig2, (ax3, ax4) = plt.subplots(1, 2, figsize=(13.5, 5.8))

# Panel A: Despinning timescale vs Q for different bodies
Q_grid = np.array([float(x) for x in data_tau['Q']])
tau_io = np.array([float(x) for x in data_tau['Io_yr']])
tau_moon = np.array([float(x) for x in data_tau['Moon_yr']])
tau_titan = np.array([float(x) for x in data_tau['Titan_yr']])
tau_merc = np.array([float(x) for x in data_tau['Mercury_yr']])
tau_venus = np.array([float(x) for x in data_tau['Venus_yr']])
tau_earth = np.array([float(x) for x in data_tau['Earth_yr']])
tau_mars = np.array([float(x) for x in data_tau['Mars_yr']])

ax3.plot(Q_grid,
         tau_io,
         'y-',
         lw=2.4,
         label=r'Io (Jovian Tides, $a = 5.9\,R_J$)')
ax3.plot(Q_grid,
         tau_moon,
         'k-',
         lw=2.4,
         label=r'Moon (Earth Tides, $a = 60\,R_\oplus$)')
ax3.plot(Q_grid,
         tau_titan,
         'c-',
         lw=2.2,
         label=r'Titan (Saturnian Tides, $a = 20\,R_S$)')
ax3.plot(Q_grid,
         tau_merc,
         'r-',
         lw=2.4,
         label=r'Mercury (Solar Tides, $a = 0.387\,\mathrm{AU}$)')
ax3.plot(Q_grid,
         tau_venus,
         'm-',
         lw=2.2,
         label=r'Venus (Solar Tides, $a = 0.723\,\mathrm{AU}$)')
ax3.plot(Q_grid,
         tau_earth,
         'b-',
         lw=2.4,
         label=r'Earth (Lunar Tides, $\tau_{\mathrm{Earth}}$)')
ax3.plot(Q_grid,
         tau_mars,
         'g--',
         lw=2.2,
         label=r'Mars (Phobos Tides, $\tau_{\mathrm{Mars}}$)')

# Critical Age Threshold (Age of Solar System = 4.5 Gyr)
T_SS = 4.5e9
ax3.axhline(T_SS,
            color='darkred',
            linestyle='--',
            lw=2.0,
            label=r'Age of Solar System ($4.5\times 10^9\,\mathrm{yr}$)')

# Shaded Zones
ax3.fill_between(Q_grid, 1e2, T_SS, color='green', alpha=0.10)
ax3.fill_between(Q_grid, T_SS, 1e18, color='red', alpha=0.08)
ax3.text(
    1.5,
    2e5,
    'SYNCHRONOUS TIDAL LOCKING REGIME\n($\\tau_{\\mathrm{despin}} < 4.5\\,\\mathrm{Gyr}$)',
    fontsize=10,
    fontweight='bold',
    color='darkgreen')
ax3.text(
    1e4,
    2e13,
    'NON-SYNCHRONOUS REGIME\n($\\tau_{\\mathrm{despin}} > 4.5\\,\\mathrm{Gyr}$)',
    fontsize=10,
    fontweight='bold',
    color='darkred')

ax3.set_xscale('log')
ax3.set_yscale('log')
ax3.set_xlabel(r'Tidal Quality Factor $Q$', fontweight='bold')
ax3.set_ylabel(r'Despinning Timescale $\tau_{\mathrm{despin}}$ [years]',
               fontweight='bold')
ax3.set_title(
    r'(a) Rotational Despinning Timescale $\tau_{\mathrm{despin}}$ vs $Q$',
    fontweight='bold',
    pad=10)
ax3.set_xlim(1.0, 1e7)
ax3.set_ylim(1e2, 1e18)
ax3.legend(loc='lower right', framealpha=0.92, fontsize=8.8)

# Panel B: Earth-Moon Tidal Recession Rate & Orbital Expansion
a_rearth = np.array([float(x) for x in data_moon['a_rearth']])
dadt_cm_yr = np.array([float(x) for x in data_moon['dadt_cm_yr']])
p_orb_days = np.array([float(x) for x in data_moon['P_orb_days']])

color = 'tab:blue'
ax4.plot(a_rearth,
         dadt_cm_yr,
         color=color,
         lw=2.6,
         label=r'Recession Rate $\dot{a} \propto a^{-11/2}$')
ax4.set_xlabel(r'Lunar Semi-Major Axis $a / R_{\oplus}$', fontweight='bold')
ax4.set_ylabel(r'Tidal Recession Rate $\mathrm{d}a/\mathrm{d}t$ [cm/year]',
               color=color,
               fontweight='bold')
ax4.tick_params(axis='y', labelcolor=color)
ax4.set_yscale('log')
ax4.set_ylim(0.1, 5000)

# Mark Present-Day Lunar Distance
ax4.axvline(
    60.3,
    color='navy',
    linestyle=':',
    lw=1.8,
    label=r'Present Moon ($a = 60.3\,R_\oplus, \dot{a} = 3.82\,\mathrm{cm/yr}$)'
)
ax4.scatter([60.3], [3.82], color='navy', s=90, zorder=5)

# Secondary Axis: Orbital Period P_orb
ax4_twin = ax4.twinx()
color_twin = 'tab:red'
ax4_twin.plot(a_rearth,
              p_orb_days,
              color=color_twin,
              linestyle='-.',
              lw=2.2,
              label=r'Keplerian Period $P_{\mathrm{orb}} \propto a^{3/2}$')
ax4_twin.set_ylabel(r'Orbital Period $P_{\mathrm{orb}}$ [days]',
                    color=color_twin,
                    fontweight='bold')
ax4_twin.tick_params(axis='y', labelcolor=color_twin)
ax4_twin.set_ylim(0, 35)

ax4.set_title(r'(b) Earth-Moon Recession Dynamics & Keplerian Period',
              fontweight='bold',
              pad=10)

lines1, labels1 = ax4.get_legend_handles_labels()
lines2, labels2 = ax4_twin.get_legend_handles_labels()
ax4.legend(lines1 + lines2,
           labels1 + labels2,
           loc='upper right',
           framealpha=0.92,
           fontsize=9)

plt.tight_layout()
fig2.savefig(os.path.join(output_dir, 'fig_model_choices.pdf'), dpi=300)
fig2.savefig(os.path.join(output_dir, 'fig_model_choices.png'), dpi=300)
plt.close(fig2)
print(f'✅ Generated {output_dir}/fig_model_choices.pdf and .png')

# ============================================================================
# FIGURE 3: fig_diagram.pdf - Tidal Bulge Lag Angle delta Schematic
# ============================================================================
fig3, ax = plt.subplots(figsize=(10.5, 6.8))

# Define geometry
r_planet = 2.2
a_sat = 7.5
delta_deg = 20.0  # Exaggerated for clear illustration
delta_rad = np.radians(delta_deg)

# Draw Central Planet (Deformed Tidal Ellipsoid)
circ_ref = patches.Circle((0, 0),
                          r_planet,
                          color='#dfe6e9',
                          ec='#b2bec3',
                          lw=1.5,
                          linestyle=':',
                          label='Unperturbed Sphere')
ax.add_patch(circ_ref)

# Deformed Tidal Bulge (Ellipse rotated by delta)
ell_major = r_planet * 1.30
ell_minor = r_planet * 0.90
tidal_bulge = patches.Ellipse((0, 0),
                              width=2 * ell_major,
                              height=2 * ell_minor,
                              angle=delta_deg,
                              facecolor='#74b9ff',
                              edgecolor='#0984e3',
                              lw=2.5,
                              alpha=0.85,
                              label=r'Tidally Deformed Bulge ($k_2, Q$)')
ax.add_patch(tidal_bulge)

# Orbit Path of Satellite
orbit_arc = patches.Arc((0, 0),
                        2 * a_sat,
                        2 * a_sat,
                        theta1=-40,
                        theta2=40,
                        color='#636e72',
                        linestyle='--',
                        lw=1.8,
                        label='Satellite Orbit')
ax.add_patch(orbit_arc)

# Satellite Position on x-axis (Sub-satellite line along x-axis)
sat_x = a_sat
sat_y = 0.0
sat_circle = patches.Circle((sat_x, sat_y),
                            0.55,
                            facecolor='#fdcb6e',
                            edgecolor='#e17055',
                            lw=2.2,
                            zorder=10)
ax.add_patch(sat_circle)
ax.text(sat_x,
        sat_y - 0.95,
        'Perturbing Satellite\n($M_s$, Mean Motion $n$)',
        ha='center',
        fontweight='bold',
        fontsize=10.5)

# Center of Mass Marker
ax.scatter([0], [0], color='black', s=80, zorder=10)
ax.text(0,
        -0.4,
        'Planet Center ($M_p, R_p$)',
        ha='center',
        fontweight='bold',
        fontsize=10)

# Line of Centers (Sub-Satellite Axis, x-axis)
ax.plot([0, a_sat + 0.8], [0, 0], color='#2d3436', linestyle='-', lw=1.8)
ax.text(a_sat / 2,
        -0.35,
        r'Line of Centers ($a$)',
        ha='center',
        color='#2d3436',
        fontweight='bold',
        fontsize=11)

# Major Axis of Tidal Bulge
x_bulge_axis = (ell_major + 1.2) * np.cos(delta_rad)
y_bulge_axis = (ell_major + 1.2) * np.sin(delta_rad)
ax.plot([-x_bulge_axis * 0.8, x_bulge_axis],
        [-y_bulge_axis * 0.8, y_bulge_axis],
        color='#d63031',
        linestyle='-.',
        lw=2.0,
        label='Tidal Bulge Symmetry Axis')

# Lag Angle Delta Arc
arc_lag = patches.Arc((0, 0),
                      4.2,
                      4.2,
                      theta1=0,
                      theta2=delta_deg,
                      color='#d63031',
                      lw=2.5)
ax.add_patch(arc_lag)
ax.text(2.3 * np.cos(delta_rad / 2),
        2.3 * np.sin(delta_rad / 2) + 0.15,
        r'Tidal Lag Angle $\delta = \frac{1}{2Q}$',
        color='#d63031',
        fontweight='bold',
        fontsize=12)

# Gravitational Force Vectors from Bulges to Satellite
near_x = ell_major * 0.75 * np.cos(delta_rad)
near_y = ell_major * 0.75 * np.sin(delta_rad)
far_x = -ell_major * 0.75 * np.cos(delta_rad)
far_y = -ell_major * 0.75 * np.sin(delta_rad)

ax.scatter([near_x, far_x], [near_y, far_y], color='#0984e3', s=70, zorder=10)
ax.text(near_x + 0.2,
        near_y + 0.3,
        'Near Bulge (+)',
        color='#0984e3',
        fontweight='bold',
        fontsize=10)
ax.text(far_x - 0.3,
        far_y - 0.4,
        'Far Bulge (-)',
        color='#0984e3',
        fontweight='bold',
        fontsize=10)

# Force arrows from satellite to bulges
ax.annotate('',
            xy=(sat_x, sat_y),
            xytext=(near_x, near_y),
            arrowprops=dict(arrowstyle='->',
                            color='#e84393',
                            lw=2.2,
                            linestyle='-'))
ax.text((near_x + sat_x) / 2, (near_y + sat_y) / 2 + 0.35,
        r'$\vec{F}_{\mathrm{near}}$ (Stronger)',
        color='#e84393',
        fontweight='bold',
        fontsize=10.5)

# Planetary Spin Vector Omega_p and Orbital Mean Motion n
spin_arc = patches.Arc((0, 0),
                       3.0,
                       3.0,
                       theta1=60,
                       theta2=120,
                       color='#00b894',
                       lw=2.5)
ax.add_patch(spin_arc)
ax.annotate('',
            xy=(-1.5 * np.sin(np.radians(30)), 1.5 * np.cos(np.radians(30))),
            xytext=(-1.5 * np.sin(np.radians(28)),
                    1.5 * np.cos(np.radians(28))),
            arrowprops=dict(arrowstyle='->', color='#00b894', lw=3.0))
ax.text(0,
        1.8,
        r'Planetary Spin $\vec{\Omega}_p$ ($\Omega_p > n$)',
        color='#00b894',
        fontweight='bold',
        ha='center',
        fontsize=11.5)

# Satellite Orbit Arrow n
ax.annotate('',
            xy=(sat_x, 1.8),
            xytext=(sat_x, -0.2),
            arrowprops=dict(arrowstyle='->', color='#e17055', lw=2.2))
ax.text(sat_x + 0.3,
        1.0,
        r'Orbital Motion $\vec{n}$',
        color='#e17055',
        fontweight='bold',
        fontsize=11)

# Torque Box Annotations
torque_text = (
    "Secular Tidal Torque Tensor (Goldreich & Soter 1966):\n"
    r"• Specific Dissipation Factor: $Q^{-1} \approx 2\delta \rightarrow \delta = 1 / (2Q)$"
    "\n"
    r"• Planetary Retarding Torque: $T_p = \frac{3}{2}\frac{G M_s^2 R_p^5}{a^6}\frac{k_2}{Q} \rightarrow \dot{\Omega}_p < 0$ (Spin Damping)"
    "\n"
    r"• Satellite Orbital Acceleration: $\frac{\mathrm{d}a}{\mathrm{d}t} = 3\frac{k_2}{Q}\frac{M_s}{M_p}\left(\frac{R_p}{a}\right)^5 n a \rightarrow \dot{a} > 0$ (Recession)"
)
ax.text(0.50,
        0.05,
        torque_text,
        transform=ax.transAxes,
        ha='center',
        va='bottom',
        bbox=dict(boxstyle='round,pad=0.6',
                  facecolor='#f8f9fa',
                  edgecolor='#2d3436',
                  alpha=0.95),
        fontsize=10.2,
        family='sans-serif')

ax.set_xlim(-3.5, 9.2)
ax.set_ylim(-3.2, 3.8)
ax.set_aspect('equal')
ax.axis('off')
ax.set_title(
    r'Physical Mechanism of Tidal Friction: Viscoelastic Bulge Lag $\delta = 1/(2Q)$ and Torque Coupling',
    fontweight='bold',
    pad=15,
    fontsize=13)

plt.tight_layout()
fig3.savefig(os.path.join(output_dir, 'fig_diagram.pdf'), dpi=300)
fig3.savefig(os.path.join(output_dir, 'fig_diagram.png'), dpi=300)
plt.close(fig3)
print(f'✅ Generated {output_dir}/fig_diagram.pdf and .png')

print("🎉 All publication figures successfully created!")
